// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcofuuudpdjadfyxwiam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjb2Z1dXVkcGRqYWRmeXh3aWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAwMjYyMzQsImV4cCI6MjA0NTYwMjIzNH0.mQxQyOJbYaKO7zBUTZNrLgvenqQ5m6BQqN5SOOrcqEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);